#configuration

#日志打印开关
#["trace", "debug", "info", "warn", "error", "fatal"]  default: "error"
log_level = "debug"

#新mongo集群地址 https://docs.mongodb.com/manual/reference/connection-string/
match_cluster_mongo_addr = "mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]"

#本地cache最大内存  128*1024*1024
memory_cache_size =  157810688

#rds
[rds]
redis_addr = "117.50.7.73:6379"
redis_live_addr = "17.50.7.73:6379"
redis_cluster_addr = "117.50.7.73:6379,117.50.7.73:6380,117.50.7.73:6381"
pika_addr = "117.50.7.73:6379"

#mysql
[rdb]
#address = "root:devchj@theL0805@tcp(localhost:3306)/stay?charset=utf8-mb4&loc=Asia/Shanghai"
master_address = "root:qwe123@tcp(localhost:3306)/stay?charset=utf8mb4&parseTime=true&loc=UTC"

[cassandra]
addresses="127.0.0.1"

[rpc]
search_rpc_addr = ""
