#configuration
port = 3200

#日志打印开关
#["trace", "debug", "info", "warn", "error", "fatal"]  default: "error"
log_level = "debug"

#新mongo集群地址 h
# match_cluster_mongo_addr = ""
# match_cluster_mongo_addr = ""
match_cluster_mongo_addr = ""

#本地cache最大内存  128*1024*1024
memory_cache_size =  1

#rds
[rds]
redis_addr = ""
# redis_live_addr = ""
redis_live_addr = ""
redis_cluster_addr = ""
common_redis_addr = ""
pika_addr = ""
behavior_addr = ""
aws_redis_addr = ""

#mysql
[rdb]
#address = ""
master_address = ""

[cassandra]
addresses=""

[influxdb]
addr = ""
token = ""
org = ""
bucket = ""

[rpc]
search_rpc_addr = ""
chatroom_rpc_addr = ""
live_rpc_addr = ""
api_rpc_addr = ""
ai_search_rpc_addr = ""