#configuration
port=3200

#日志打印开关
#["trace", "debug", "info", "warn", "error", "fatal"]  default: "error"
log_level = "debug"

#新mongo集群地址 
match_cluster_mongo_addr = "127.0.0.1:27017"

#本地cache最大内存  128*1024*1024
memory_cache_size =  157810688

#rds
[rds]
redis_addr = "127.0.0.1:6379"
redis_live_addr = "127.0.0.1:6379"
redis_cluster_addr = "127.0.0.1:6379"
pika_addr = "127.0.0.1:6379"
behavior_addr = "127.0.0.1:6379"
aws_redis_addr = "127.0.0.1:6379"

#mysql
[rdb]
#address = ""
master_address = "127.0.0.1:3306"

[cassandra]
addresses="127.0.0.1"

[influxdb]
addr = "http://127.0.0.1:8086"
token = "XQHRwz4xAsn8fG_QKYbHxEL__5klkKWeh94_8cMRx12PuWn1yuJiHW8ebd3g6qtxrlnsTZ3I_cYyZ2gqecVLag=="
org = "freechat"
bucket = "ai"

[rpc]
search_rpc_addr = "127.0.0.1"
api_rpc_addr = "http://127.0.0.1"
chatroom_rpc_addr = "127.0.0.1"
live_rpc_addr = "127.0.0.1"
ai_search_rpc_addr = "127.0.0.1"
